services:
  mc:
    image: itzg/minecraft-server:2026.2.1
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
      - "./plugins:/plugins"
      - "./extra-config:/extra-config"
      - "./mods.txt:/mods.txt"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.11" # Minecraft version
      TYPE: "PAPER" # Run PaperMC
      PAPER_BUILD: "123" # Specify version of PaperMC
      MEMORY: "6G"

      # Server Properties
      MOTD: "Electric Mayhem"
      DIFFICULTY: "hard"
      OPS: |
        mrdarthpyro
        reallyjoey
      VIEW_DISTANCE: 16

      MODRINTH_PROJECTS: "@/mods.txt"
      APPLY_EXTRA_FILES: |
        ./</extra-config/bukkit.yml
        ./</extra-config/commands.yml
        ./</extra-config/spigot.yml
        ./</extra-config/wepif.yml
        config</extra-config/config/paper-global.yml
        plugins/BookGUI/books</extra-config/plugins/BookGUI/books/
        plugins/DiscordSRV</extra-config/plugins/DiscordSRV/config.yml
        plugins/Essentials</extra-config/plugins/Essentials/config.yml
        plugins/Essentials</extra-config/plugins/Essentials/motd.txt
        plugins/Essentials</extra-config/plugins/Essentials/rules.txt
        plugins/GriefPreventionData</extra-config/plugins/GriefPreventionData/config.yml
        plugins/LuckPerms</extra-config/plugins/LuckPerms/config.yml
        plugins/LuckPerms/yaml-storage/groups</extra-config/plugins/LuckPerms/yaml-storage/groups/
        plugins/Skript/scripts</extra-config/plugins/Skript/scripts/
        plugins/WorldGuard</extra-config/plugins/WorldGuard/config.yml
        plugins/bStats</extra-config/plugins/bStats/

